language: java
jdk:
  - openjdk11
services:
  - postgresql
before_install:
  - psql -c 'create database tracker;' -U postgres
sudo: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
      - ilya.moskovtsev@gmail.com
    on_success: never # default: change
    on_failure: always # default: always